export default function() {
    const silent = [
        "                                        ..';codxkOOOOOOkxdoc;..                                     ",
        "                                    .,cok0KXNNNNNNNNNNNNNNNXK0ko;..                                 ",
        "                                .'cdOKNNNWWWWWNNNNNNNNNNNNNNNNNNKOxc'.                              ",
        "                             .'cx0XNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNX0xc'                            ",
        "                           .;d0XNNNNNWWWWWWWWWWWWNNNNNNWWNNNNNWNNNNNNNX0d;.                         ",
        "                         .:xKNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNKx:.                       ",
        "                       .:xKNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNXk:.                     ",
        "                     .:xKNNNNNNXXXNNNNNWWWWWWWMMMMWWWWWWWWWWWWWWNNNNNNNNNNNNNKd,                    ",
        "                   .;xKNNNNNNNXXXXNNNNWWWWWWWMMMMMMMMMMMMMWWWWWWNNNNXXXXXNNNNNXOl.                  ",
        "                 .;dKNNNNNNNNNXXXNNNNWWWWWMMMMMMMMMMMMMMMMMMMWWWWNNNXXXXXXXXNNNNXx;.                ",
        "                ,d0XNXNNNNNNNNNXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWNNNXXXXXXXNNNNNX0l.               ",
        "              .ckXXXXXXXXXXNNNXXNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMWWWNNNNXXXXXXXXXXNNNKx,              ",
        "             .o0XNXXXXXXXXXNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNXXXXXXXXXNNNNXk;.            ",
        "            'dKNNXXXXXXXXXNNNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWMMWWWWNNNNNXXXXXXXXNNNNXO:.           ",
        "           .dKNNNNNXXXXXXXXXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWNNNNNNNNXXXXXXNNNXO:.          ",
        "          .c0NWNNNXXXXKKKKXXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNXXXXXXXNXk;          ",
        "          .dXWWNNNNXXK000KKKK000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNXXXXXXXXXKd.         ",
        "          'xXWWWNNNXKK0OkxddolllodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNNXXXXXXXXXXXXXOc.        ",
        "          ,kNWWWWNNXX0kxxxxxkkxdoodxk0KXXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KXXXXXXXXKK0d.        ",
        "          ,kNWWWWNNXKOO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO0OOOOkkOKXXXXXXKK0x,        ",
        "          ,ONWWWWWNXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNWWNNXXK000KXXXXXKK0x,        ",
        "          ;ONWWWWNNNX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXKKKXXXXXKK0d,        ",
        "          ;ONWWWNNNX000K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKKKXXXXKKK0d'        ",
        "         .:0NWWNNNXXKK0Oxdoooc,',;cxdllx0XKxdk0XNWWWWNX0kdxO0kdodxxkOOOOOOOOO0000KKXXXKKKOo.        ",
        "        .cOXWWNNNNNNXKOxo::xk:..;,,kKkolx0NX00KKNNWWNNXXKKXKxlldd;.,;',odooodk0000KKXXKKKOc.        ",
        "        'dKWWWWNNNNNNNXXK0xdxocldddOXKKKKXXKKKXNWWWWWNXXXNNXOO0XOc;lc.:OOo;;cok0KKXXXKKKKx;         ",
        "        'l0WWWNNNNNNNNNXXK0OkkOKXNNNNNWWNNXXXXNWWWWWWNNXXNNNWWNNXK00OxxkxddkO0KXXXXXXKKK0d:.        ",
        "       .:OXWWNNNNNNWWWWWWWWWWWWWWWWWWWWWNNNNNWWWWWWWWWNNNNNNWWWWWWWWNXXK0O0KXNNNNNNNXXKK00kl'       ",
        "       .dXNWWWWNNNWWWWWWWMMMWWWWMMMMWWWNNNNNWWWWWWWWWWWNNNNWWWWWMMWWWMMMWWWWWWNNNNNNXXKKKk:,'.      ",
        "       'xXNWWWWWWWWWWWWWMMMMMMMMMMMMWWNNWWWWWWWMMMMMWWWWWNNNWWMMMMMMMMMMMMMWWWWWWNNNXXKKOl,,.       ",
        "       ,xXNWWWWWWWWWWWWWMMMMMMMMMMWWWWWWWWWWWWMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMWWWWWNNNXXXXXOdl'       ",
        "       'xXNNWWWWWWWWWWWWWMMMMMMMWWWWNNNNNNNXNNWWWWWWWNNWWWWWWWWMMMMMMMMMMMMMMWWWWWNNXXKKXKOd'       ",
        "       .dXNNWWWWWWWWWWWWWWWWMMWWWWNKkxdlc::coOKXXXXK0OkO0KXNNNNWMMMMMMMMMMMMWWWWWWNNXKKKKX0o.       ",
        "       .oKNNNWWWWWNNWWWWWWWWWMWWWNXkc,'......;lodddoc,.'',:odk0NWMMMMMMMMMWWWWWWWNNNXKKXNXO:.       ",
        "       .oKNXNNNNNNNNNNNWWWWWWWWWNNNKOdlloodddl:;:cclooolc;'';oONWWWMMMMMWWWWWWNNNNNXXKKXNKo.        ",
        "      .:OXNXXXNNNXXXXNNNNNWWWWWNNNNNNNNNNNNWWNK00KXXNNNXKOkO0KXNWWWWWWWWWWWWWNNNNXXK00KXKx'         ",
        "      .ckOKXKKXXXXXKKXXXXNNWWWNNNNNNNNWNWWWWWWWWWWWWWWWWNNNNNWWWWWWWWWWWWWNNNNXXXXK0OOKXO:.         ",
        "       .';d0K00KKKKKXXXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWNNWWNNNNWWWWWNNNNNXXXKK0OOk0K0o.          ",
        "         .;kKK000KKKKXXXNNNNNNNNNNNXXXXXXNNNNWWWWWWWWWWWNNNNNWNNNNNNNNNNNXXXKKK0OOkkk0K0l.          ",
        "          'dKK0000KXXXNNNNXXXXXX0kxdddolodkO00KXXXXXKKK000KKKXNNNNXNNNNNXXK000OOkkkkkxddc.          ",
        "          .lO0000KKXXNNNNXXXK0kd:,,,,'',:ooxkOOOxkOkkkdl::clooxOKXXXXNNXXXKK00OOkkkko;'..           ",
        "           :k000000KXXNNNXXXX0kxdooxxxxkOOOKXXNKxkKXXXKxlloolc:;cx0KXXXXXXXK00OOkkkd;               ",
        "           'dO0OOOOO0KKKKKKXXXKKXNNNNNWWWWWWWNNNKXNNWWWWNNNNXK0xxkOKXXKXXXK00OOOkkkl.               ",
        "           .ckkxxxkkkOOOOO0KXNNXKKKXXXNNWWMMMMMMMMMMMMMMWWNXXNNXXXXNXXKKK00OOOOkkkx;                ",
        "            ,dkxddddddddxxk0XXNNX0kkxkkO0XNWWWWWWWWWMMWWNXKKKKKKXNNXXK00OOOOkkkxkkl.                ",
        "            ;ddoolllllllodxk0KXXXKOxl:;;;coxO00KKKKKK0OkxxxkkO0XNNXXK0Okkkxxxxddxd,                 ",
        "           .lko::c:cccccloodkOKKXK0kdc,.........''''''',;codk0KXXXXK0kxxxxdoollooo:,..              ",
        "        .;cllc'..',,,;::cloxkO0KKKK0kdl:,'.'.. .......;lddkO0KXKKKK0kddddolcccc:,,;cllc:,.          ",
        "     .;ool:,...  .....',;:loxO00KKXXK0Okdoc:;',;lodooxO0KKKXXXXK00Okxdollcc::;,......,:lool;..      ",
        "  .,lddc'.  ...     . ....';clodxO0KXXK0OOO00OO0KXXXNWWNNNNNXXXK0kkdllc:;;;,'..     ....':x0Oxo:..  ",
        ";cxkdc'.     ..         ......',;loxkOOOOkO0XXX0O00KXNXXXXXXK00Oxo:,,;,'''...      .. ...;ldk0KKOd:'",
        "0kxd:'..      .       ...........'';::cccccoxxdoooodxkxoodxxdddl:;...........    ........;coxO0KXXK0",
        "kxdl;..            ......................';,'',,,,',,;,'',;;,,,'............   .........,coodxO0KXNN",
        "dddl;.              .... ....     .. ..  ...............................'....   .......,coooxkOkO00K",
        "doodl,....           .........        .   ......      ..........    ......'........',,,cddddk0KKK0kk",
        "xdlol;........       .........         ...  ...        ....   ..   ......''.. .....',,lxxxxxk0KXX0xl",
        "xdolc,'..........    .........         ...     .       ..'..  .. ........''.   ....';cdxkOkxk0KOddxx",
        "kxdoc::'...,,...   ..........   ..                   .....'.. ..........'''.   ...;codxxxkxkOkdddxkx",
        "Okkxool::,'',,..     ........     ..                .......'............'''.   ..':loddxkkxdooodxxOO",
        "k000Okxxdl::;,...... ...  ... .. ....                .... ........ ....''''.  ..';codxkkxdolddolodxx",
        "ldkOkxxxddoc:;;'.........     .....                       .............',,'.  .'cdkOkxxdoooc;,;clllo",
        ";ccoddxxxdoc;;,............   .....                       ...   ....''';;,'.  .:dkxxol:;;'.    .:odo",
        "..':cldxolll:;,,............  .....                             ..,,,;;;;,'. .cddoc:;'.      ..,cooo",
        "   ';clccodoccc;'..','.......         .    ..     ..         ...,;;,,;;;;;'.,codoc,....    .cxO00Okx",
        "  ...:oollllccc;;,'';:;,'....        ...  ............... ....',;:;;;:::::;;lol;;,.   .   .,clodxO0K",
        "''.....,;cc:ccodxdl:;;::;;,..        .........................,;;;:cc:;;,'..,:;,,.........',;,,,,;ld",
        "..       .,;,;:cldxxdollcc:,..         ................... ..,;:ccc;,,'''...',:cccll,..''..',',,;:co",
        "....         ....',;:c:cclc:,.             .............  ..,:lll:,,;;'.....,lkolol:;',,;;:cccccclld",
        ".';;'.           ..','..',,'......               .........,:lol:,,'.,,...'',coo:,,;;,;cloooooddooodd",
        ";;;;;,...            ..''''..                       .....;coo;'''''.....':;:c;,,;:cccllcllccloooodll",
        "c:;:::;,'.....                                      ...';col;'''..''....''.','';cllolcllodoodooooddl",
        "cc:;;:;,''''....                        .            ...,:c;'.'','.........,'';cllllolloodddxxxkxxdo"
    ]
    const blink = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkOOOO00KKXXXXXXNNNWWWWWNNNNNNXXXKKK00OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKKXXXNNNWWWWWWWWWWWWWWWNNXXXKK0OOOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXXNNNNWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO000KKKKXXXNNNNWWWWWWWWMMMMMMMMMWWWWWNNXK00OOOkkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOOO0KKKKKXXXNNNNWWWWWWWWWWWMMMMMMMWWWWWNNXXKK00OOOkkkkkkkkkxl'              ",
        "             .:dxxxxxkkkOO00KKXXXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXXKK000OOkkkkkkkkko,.            ",
        "            .cxkxxxkkkkO00KKKXXXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXKK000OOkkkkkkkxo;.           ",
        "           .cxkkxkkkkOO000KKKXXNNNWWWWWWWWWWMMMMMMMMMMMMMWWWWWWWWWWWNNXXXXKK00OOkkkxxkxo,.          ",
        "          .;dkkkkkkkOOOOO00KKXXXXNNWWWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWNNNNXXXKK0OOkkxxxxxl'          ",
        "          .cxkkOOOOOOOOOOOOOOOO000KXXNWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWNNNNNNNXXKK0OOkkxxxxdc.         ",
        "          .lxkOO000000OkxxdddooddxxO0KXXNNNWWWWMMMMMMMMMMMMMWWWWNXXXKK0KKXXXKKK000Okxxxxdo;.        ",
        "          'lkOO00KKK0OxxxxkkkOkxxxxkkOO0KKXNNNWWWWWWWWWWWWWWNNXK0OkxdddxkOOOOOO000Okkxdddoc.        ",
        "          'okO0KKKXK0OOOO00KKXXK00OkkxxkkO00KKXXXNNNNNNNNNXXKK0OkxddxxkO00OOkkkkO0OOkxddooc'        ",
        "          'ok00KKXXKKK0O00KKXXXXXXK0OkxdooodxkO00KKKKKKK00Okxxxdxxk0KKXXNXXXK00OkOOOkxxdooc'        ",
        "          'oO0KKXXXK0OOO0KKKKKKXXXXK0OkxdolccloxkOOOOOkkxdllllodkO0XXNNNXXXXKKK0OOOOkxddolc.        ",
        "          'oO0KKXXK0OOO0KKK000KKXXKK0Okdddol:coxkO000kxdolcclodxkOKXNNXXKKKKK00000OOkxddol:.        ",
        "         .;dO0KKXXK0OOOOOOOOOOOOOOkkxxdollodooxkO00000kxdlcllooxkO0KXXXK00OOOOOOOOOOkxddol:.        ",
        "        .;okO0KKXXKK00OOxddxkkkkkxxdooooodxkkxkOO0000OOOkxddddddxxkOO000OkkkkkkkkkOOkxddol,.        ",
        "        .:dOO0KKXXKK0000Okoc:c::::;,,;cldOOOkkO0KKKKK0OOOO00OxollodxkkOOOxdooooxkOOOkxddoc'         ",
        "        .;okO00KKKK000000OkdoollloddxkO0000OO00KXXXKK0OOOO0KKOxl:::::clol:::codkO00Okxddoc,.        ",
        "       .,lxOOO0KKKKK000000000KKKKKKKKKXKK0000KKXXXXKK0OkkO0KKXXK0OxollolcccoxkOO0K00kxddool;.       ",
        "       .cdkOO00KXXXXXKKKKXXXXXXXXXXXXXXK00000KKKKKKKKK0OOkO0KXXXXXXXKKKK0OOOOO0KKKK0kxdddl,..       ",
        "       .lxkOO0KKXNNNNNXXXNNNNNNNNNNNXK0000000KXXXXXXXKK00OOO0XXNNNNNNNNXXXXKKKKKKKK0Oxddo,.'.       ",
        "       .lxkOO0KKXNNNNNNNNNNNNNNNNNXXK00KKK00KKXNNNNNXKK0000OOKXNNNNNNNNNNNNNNXXXXXK0Oxddxo:;.       ",
        "       .lxkkO00KXXXNNNNNNNNNNNNNXXK0OOOOOOkxkO0KKKKK0OO00K0000KXNNNNNNWWWWWWNNNNXXK0kxddddoc.       ",
        "       .cxxxkO00KKKKKKKXXXXXXXXXKKOdlc:;,,,,:odxkkxxdolodkkOOOOKXNNNNNNNNNNNNNNXXK0Okxddddd:.       ",
        "       .:dxxxkOOOOO000000KKKKKKK0Oxl,.........;:::::,.....';cldOKXXXNNNNNXXXXXKKK0OkxddxOko,        ",
        "       .:dxdxxkkkkkkOOOOO000KK00Okkxoc;;:::cc;''',,;::;,,...';ok0KKXXXXXKKK00000OOkxdddk0x:.        ",
        "       ,oxxdddxxxxxxxkkkkOOO00OOOOOkkkkkkOO00OkkkkkOOOOkxdoodxkO000KKKKK000OOOkkkxxdoooxxc.         ",
        "      .,llodoodddddddxxxxkkOOOOkOkkkOOOOO000KKKKKKKKK00OOOOOOOOOOO000000OOOkkkxxxdoolldxl,.         ",
        "       ..':lllloooodddxxxkkkkkkkkOOOOOOOOOO0000KKKKKK000OOOOOOOkkkOOOOOOkkkxxxxddolllldo:.          ",
        "          ,coollloooddxxxxxkxxxkOOkkxxxxxkkkkO0000000OOOOkkOOOkkkkkkOOkkxxxddddolllccodo:.          ",
        "          .:oolllooddxxxkxxdddxdolc:::;;;:looddxkkkxxdddoodddxkOkkxxkkkxxddoooolllccc::c,.          ",
        "          .;llllloodxxxxkxdddll:'.......';;clooolllllc:;',,;;:coxxxxxxxxxdddoollcccc:'...           ",
        "           'cllllllodxxxxxdddoccc:cllloodooxkkOxclxkkkxl;::::;'',codxxddddddoollccc:'               ",
        "           .:lllllllooodddddxxdodkkOkOO0KKXXKKK0OO0KKKKK00OOkxdlccloxdddxddooolllcc;.               ",
        "           .,cc::ccccccllloodxxxdodxxxxk0KXNNXXXNNNNNNNXK0kxxkkxxxxxxddddooollllcc:'                ",
        "            ':::;;;;::::::codxxxdocccccldkO0KKKKKKKXXXK0kxddddddxkkxddoollllllcccc;.                ",
        "            '::;;,,;;;,;;;:cldddddl:;'..',:lodxxxxxxxdolcccccloxkxxdolllccccc:::c:'                 ",
        "           .;l;''''',,,,,;;:clodddoc:,..  ..............',;:lodxxxxdlcccc::;;;;;;:,...              ",
        "        .';;;,........'',,;:cllodddoc:;'.....    ......,::clodddddool::::;,,,,,'..',;;;,..          ",
        "     .'::;'....   .......',;:clooddddolc:;,'...',::;:looddddddddoolc::;;,,,'''..   ...';:::,..      ",
        "  .';c:,.    .          ....';;:clodxxdolllooooodxxxkOOOOkkkxxddolc:;;,'''....        ...'coolc,.   ",
        "';cl:,..                   .....',;:lollllloxkxdooddxkxxxxxxdoolc;'..'......            ..,:codxdc,.",
        "olc:'..                 .    .......'',,,,,;cc::;;;:ccc:;:cc:::;'.........              ..,;:clddxxo",
        "cc:,..                   .        ................................ .   ...      .    ....,;;;clldxkO",
        ";:;,..                    .               .....  ..    .......        ......       .....';;;:clcloox",
        ":;;;,..               .. ....                          ....          .......     ......,::;:codddoll",
        ":;;;,'....           ........                          ...            ......    ......,:::::cldxxdc,",
        "c:;,'.........        ...   .                          ....        .........    .....,::ccc:codlc:cl",
        "c:;;,''.......        ....                             .....      ..........   ....,;;::ccclol::cllc",
        "llcc;;;''.......      .. ..                          ...  ... ..   .........    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....                                       .   .....    ........   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'...      ..      .  .                         ....  ...........   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....               ...                               .......'...  .':llc:;,'...    .';:;",
        " ..',;::;;,,'....  ..   ...                                      ......''..  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''..........                                    ...''...'''....,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....'.....                ..     ...        ...''...'','''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..'''....                     ...       ....''',,'.......'..... .............',:",
        ".        ..'..',;cllc;;;,,'..                    ...        ..'',,,'..........'',,;;............'',;",
        "...           .....',,,,,;,'..                    .        ..,;;;,...........;c;,;,'......',',,',,;:",
        ".....             ............                           ..,;;;'............,;;'......',;;;;,;:;;;;:",
        "........              ......                           ...,:;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"
    ]
    const smile = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO0000OOOOOOOOOOOOOOkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK000000000OOO00OOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOO000KKKKKK00000000000000000OOOOOOOkdl,.                         ",
        "                         .;oxkOOOOOO00000KKKXXXXXKKKKKKKKKKK0000OOOOOOkOkxo;.                       ",
        "                       .;oxkOOOOOOO00KKKKKXXXNNNNNNXXXXXXXKKKK000OOOOOkkkOkko;.                     ",
        "                     .;lxkkkkOOOO000KKXXXXXNNNNWWWWWNNNNNNXXXKKK00OOOkkkkkOOkxl'                    ",
        "                   .,lxkkkkOOOO00KKKXXXNNNWWWWWWWWWWWWWWWWNNNXXKK00OOOkkkkkkkOkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXNNNNWWWWWWWWWWWMMWWWWWWWWNNNXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKXXNNNWWWWWWWMMMMMMMMMMMMMMWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWWNNXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOO00KKXXXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWNNXXKK000OOkkkkkkkko,.            ",
        "            .cdkxxxkkkOO0KKXXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKK00OOkkkkkkkxo;.           ",
        "           .cxkkkkkkkOO0KKKKXXNNWWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkxkxo,.          ",
        "          .;dkkkkkkOO0000KKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNXXKK00Okkxxxxxl'          ",
        "          .cxkOOOOO000000KKK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNXXK00Okkxxxxdc.         ",
        "          .lxOO000K0000kxxddolllodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNXXKKK00Okxxxxdo;.        ",
        "          'lkO00KKKKKOxddxxxkkxdoodxk0KXXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KKK0OOkxxddoc.        ",
        "          'okO0KXXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO0OOOOkkO0K0Okxxdooc'        ",
        "          ,ok0KXXNNXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxdxkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          ,dO0KXXNNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxxdooc.        ",
        "          ,dO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okkxdol:.        ",
        "         .:xO0KXXXXXKK0Oxdoooc,',;cxdllx0XKxdk0XNWWWWNX0kdxO0kdodxxkOOOOOOOOO0000000Okxdol:.        ",
        "        .;dk00KXNNNXXKOxo::xk:..;,,kKkolx0NX000KXNNNNXXKKKXKxlldd;.,;',odooodk00O000Okxdol,.        ",
        "        .cxO0KKXXNNNNNXXK0xdxocldddOXXKKKKXK00KXNNNNXXK0KXNKOO0XOc;lc':OOo;;cok00K0Okxxdoc'         ",
        "        .:dO0KKXXXNNNNNXXK0OkkOKXNNNNNWWNXK000KXNNNNNX0000KXNNNNXK00OxxkxddkO0KXXXK0Okxdoc,.        ",
        "       .,lxO0KKXXNNNWWWWWWWWWWWWWWWWWWWNXXKKKKXNNNNNNXK0O0KXXNNWWWWWNXKK0O0KXNNNXXK0Okxdodl;.       ",
        "       .cdkO0KKXXNNNWWWWWMMMMMWWWWWWWWNXKKKKXXNNNNNNNNXKK00KXNWWWWWWWMWWWWWWWNNNNNX0Okxddl,..       ",
        "       .lxkO0KKXNNNWWWWWMMMMMMMWWWWWNXXKXXXXXXNNWWWWWNNXXKKKKXNWWWWWWMMMMMMMWWWWNNXKOkxdl,.'.       ",
        "       'lxkO0KXXNNNWWWWWWMMWWWWWWNNXKKXXXXXXXXNNWWWWWNNXXXXXXKXNWWWWWWMMMMMMWWWWNNXKOkxdxo:;.       ",
        "       .lkkkO0XXNNNNNNNWWWWWWWNNNXX0kOOOOOOOkOKXXNNNXK00KXXXXXKKXNWWWWWMMMMMWWWWNNX0Oxddddoc.       ",
        "       .cxxkO0KXXXXXXXNNNNWWNNNNNNKxc;;,,''',:oxkkkkxolcloddxkxkKNNNNWWWWWWWWWNNNXK0kxddddd:.       ",
        "       .:dxxkO00KKKKKKKKXXNNNNNNXX0kl'.........,;;;;,'.......,:d0XNNNNWWWWNNNNXXXK0OxddxOko,        ",
        "       .cdxddxxkkkkkOOO00KXXXXKKK00Okxollloool:;,;::lddolc:;:ldk0KXXXXNNNNXXXXKK00Oxxddk0x:.        ",
        "       ,oxxdddoodddddxxkk0K0OOOOOOOOOO0000KKXXXK00KKXXXKK0OOOO000KKKKXXXXXKK00OOOkxdoodxxc.         ",
        "      .,llodoollooodddxkOOxooddxkOO000K00KKKXXXXNNNNNNXXKK0000K0000KKKKKK0OOOkkkxdoolldxl,.         ",
        "       ..':oollllodddxkO0xoolldkOO00OOOOO0000KXNNNNNNNXXK000000K00OO00KK0Okkxdddollllodo:.          ",
        "          ,coooooodxxkO00OkxlclllccllcccccodddkO00000OOOxdddxxxkO00OkO000Okxdooolllclodo:.          ",
        "          .coooooodxkkO0KKK0xl:;.....,:c:cdddxOO0kxkkkkkdoc;;;::ccokkkkOOOkkxdolllllcc:c,.          ",
        "          .;lllooooodxkk0KXXKOxxxooodk00kOXKXWWWWNKXWWWWNKxol:,,'.':oxOOOOOkxxolllll:'...           ",
        "           ,cllloolllllox0KKKK0OkO0KKKKKXXNXNWWWWNXXWWWWWNXXK0kxxdodxO0000kxdoollllc,.              ",
        "           .:llllllc::::ldxOKKKKOkkOOO00KXNWWWWWWWWWWWWWWWNXK0OO00O0KKK0Okddoollllc;.               ",
        "           .,cc:::::::;;::ldk0KKK0kxdddddk0XNWWWWWWWWWWWNXKOkxkOkO0KK00Oxdolllllllc'                ",
        "            ':::;;;;;;;;,;;coxO0000kol:;,,:lxk0KXXXXXXK0OxoooddxkO000Okdolcccccccc;.                ",
        "            '::;;,,,,,,,,,;:coxO000Oko:,......',,;;:::;;;;;:clodkOO0Oxdlccc:::::c:'                 ",
        "           .;l;''''''',,,,;:codkO0000koc;'..............',;cloxkkkkxxdlcc:::;;;;;:,...              ",
        "        .';;;,........''',,;:coxkkO0K0kxol::;''.',,;c:;:coxxxkkOOkxddolc:;;,,,,'..',;;;,..          ",
        "     .'::;'....   .......''',;:cloxkO00OxdodoooooooxOOO00000000Okxdol:;;,,,'''..   ...';:::,..      ",
        "  .';c:,.    .          .....''',;:ldxkkxxdddk000OkkO0KKK0OO0Okxdol:,'''.'....        ...'coolc,.   ",
        "';cl:,..                   ......'',;:ccllccodxdoooooddxdollooll:;'.........            ..,:codxdc,.",
        "olc:'..                 .    ........'''''',::;;;;;;;;;;;,;;;;;,'.........              ..,;:clddxxo",
        "cc:,..                  ..        ...............................      ...      .    ....,;;;clldxkO",
        ";:;,..                    .               .....  ..    .......        ......       .....';;;:clcloox",
        ":;;;,..               .. ....                          ...           .......    .......,::;:codddoll",
        ":;;;,'....           ........                          ...            ......    ......,:::::cldxxdc,",
        "c:;,'.........        ...   .                          ....        .........    .....,::ccc:codlc:cl",
        "c:;;,''.......        ....                             .....      ..........   ....,;;::ccclol::cllc",
        "llcc;;;''.......      .. ..                          ...  ... ..   .........    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....                                       .   .....    ........   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'...      ..      .  .                         ....  ...........   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....               ...                               .......'...  .':llc:;,'...    .';:;",
        " ..',;::;;,,'....  ..   ...                                      ......''..  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''..........                                    ...''...'''....,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....'.....                ..     ...        ...''...'','''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..'''....                     ...       ....''',,'.......'..... .............',:",
        ".        ..'..',;cllc;;;,,'..                    ...        ..'',,,'..........'',,;;............'',;",
        "...           .....',,,,,;,'..                    .        ..,;;;,...........;c;,;,'......',',,',,;:",
        ".....             ............                           ..,;;;'............,;;'......',;;;;,;:;;;;:",
        "........              ......                           ...,:;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"
    ]

    const fv = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkOOOO00KKXXXXXXNNNWWWWWNNNNNNXXXKKK00OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKKXXXNNNWWWWWWWWWWWWWWWNNXXXKK0OOOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXXNNNNWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO000KKKKXXXNNNNWWWWWWWWMMMMMMMMMWWWWWNNXK00OOOkkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOOO0KKKKKXXXNNNNWWWWWWWWWWWMMMMMMMWWWWWNNXXKK00OOOkkkkkkkkkxl'              ",
        "             .:dxxxxxkkkOO00KKXXXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXXKK000OOkkkkkkkkko,.            ",
        "            .cxkxxxkkkkO00KKKXXXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXKK000OOkkkkkkkxo;.           ",
        "           .cxkkxkkkkOO000KKKXXNNNWWWWWWWWWWMMMMMMMMMMMMMWWWWWWWWWWWNNXXXXKK00OOkkkxxkxo,.          ",
        "          .;dkkkkkkkOOOOO00KKXXXXNNWWWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWNNNNXXXKK0OOkkxxxxxl'          ",
        "          .cxkkOOOOOOOOOOOOOOOO000KXXNWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWNNNNNNNXXKK0OOkkxxxxdc.         ",
        "          .lxkOO000000OkxxdddooddxxO0KXXNNNWWWWMMMMMMMMMMMMMWWWWNXXXKK0KKXXXKKK000Okxxxxdo;.        ",
        "          'lkOO00KKK0OxxxxkkkOkxxxxkkOO0KKXNNNWWWWWWWWWWWWWWNNXK0OkxdddxkOOOOOO000Okkxdddoc.        ",
        "          'okO0KKKXK0OOOO00KKXXK00OkkxxkkO00KKXXXNNNNNNNNNXXKK0OkxddxxkO00OOkkkkO0OOkxddooc'        ",
        "          'ok00KKXXKKK0O00KKXXXXXXK0OkxdooodxkO00KKKKKKK00Okxxxdxxk0KKXXNXXXK00OkOOOkxxdooc'        ",
        "          'oO0KKXXXK0OOO0KKKKKKXXXXK0OkxdolccloxkOOOOOkkxdllllodkO0XXNNNXXXXKKK0OOOOkxddolc.        ",
        "          'oO0KKXXK0OOO0KKK000KKXXKK0Okdddol:coxkO000kxdolcclodxkOKXNNXXKKKKK00000OOkxddol:.        ",
        "         .;dO0KKXXK0OOOOOOOOOOOOOOkkxxdollodooxkO00000kxdlcllooxkO0KXXXK00OOOOOOOOOOkxddol:.        ",
        "        .;okO0KKXXKK00OOxddxkkkkkxxdooooodxkkxkOO0000OOOkxddddddxxkOO000OkkkkkkkkkOOkxddol,.        ",
        "        .:dOO0KKXXKK0000Okoc:c::::;,,;cldOOOkkO0KKKKK0OOOO00OxollodxkkOOOxdooooxkOOOkxddoc'         ",
        "        .;okO00KKKK000000OkdoollloddxkO0000OO00KXXXKK0OOOO0KKOxl:::::clol:::codkO00Okxddoc,.        ",
        "       .,lxOOO0KKKKK000000000KKKKKKKKKXKK0000KKXXXXKK0OkkO0KKXXK0OxollolcccoxkOO0K00kxddool;.       ",
        "       .cdkOO00KXXXXXKKKKXXXXXXXXXXXXXXK00000KKKKKKKKK0OOkO0KXXXXXXXKKKK0OOOOO0KKKK0kxdddl,..       ",
        "       .lxkOO0KKXNNNNNXXXNNNNNNNNNNNXK0000000KXXXXXXXKK00OOO0XXNNNNNNNNXXXXKKKKKKKK0Oxddo,.'.       ",
        "       .lxkOO0KKXNNNNNNNNNNNNNNNNNXXK00KKK00KKXNNNNNXKK0000OOKXNNNNNNNNNNNNNNXXXXXK0Oxddxo:;.       ",
        "       .lxkkO00KXXXNNNNNNNNNNNNNXXK0OOOOOOkxkO0KKKKK0OO00K0000KXNNNNNNWWWWWWNNNNXXK0kxddddoc.       ",
        "       .cxxxkO00KKKKKKKXXXXXXXXXKKOdlc:;,,,,:odxkkxxdolodkkOOOOKXNNNNNNNNNNNNNNXXK0Okxddddd:.       ",
        "       .:dxxxkOOOOO000000KKKKKKK0Oxl,.........;:::::,.....';cldOKXXXNNNNNXXXXXKKK0OkxddxOko,        ",
        "       .:dxdxxkkkkkkOOOOO000KK00Okkxoc;;:::cc;''',,;::;,,...';ok0KKXXXXXKKK00000OOkxdddk0x:.        ",
        "       ,oxxdddxxxxxxxkkkkOOO00OOOOOkkkkkkOO00OkkkkkOOOOkxdoodxkO000KKKKK000OOOkkkxxdoooxxc.         ",
        "      .,llodoodddddddxxxxkkOOOOkOkkkOOOOO000KKKKKKKKK00OOOOOOOOOOO000000OOOkkkxxxdoolldxl,.         ",
        "       ..':lllloooodddxxxkkkkkkkkOOOOOOOOOO0000KKKKKK000OOOOOOOkkkOOOOOOkkkxxxxddolllldo:.          ",
        "          ,coollloooddxxxxxkxxxkOOkkxxxxxkkkkO0000000OOOOkkOOOkkkkkkOOkkxxxddddolllccodo:.          ",
        "          .:oolllooddxxxkxxdddxdolc:::;;;:looddxkkkxxdddoodddxkOkkxxkkkxxddoooolllccc::c,.          ",
        "          .;llllloodxxxxkxdddll:'.......';;clooolllllc:;',,;;:coxxxxxxxxxdddoollcccc:'...           ",
        "           'cllllllodxxxxxdddoccc:cllloodooxkkOxclxkkkxl;::::;'',codxxddddddoollccc:'               ",
        "           .:lllllllooodddddxxdodkkOkOO0KKXXKKK0OO0KKKKK00OOkxdlccloxdddxddooolllcc;.               ",
        "           .,cc::ccccccllloodxxxdodxxxxk0KXNNXXXNNNNNNNXK0kxxkkxxxxxxddddooollllcc:'                ",
        "            ':::;;;;::::::codxxxdocccccldkO0KKKKKKKXXXK0kxddddddxkkxddoollllllcccc;.                ",
        "            '::;;,,;;;,;;;:cldddddl:;'..',:lodxxxxxxxdolcccccloxkxxdolllccccc:::c:'                 ",
        "           .;l;''''',,,,,;;:clodddoc:,..  ..............',;:lodxxxxdlcccc::;;;;;;:,...              ",
        "        .';;;,........'',,;:cllodddoc:;'.....    ......,::clodddddool::::;,,,,,'..',;;;,..          ",
        "     .'::;'....   .......',;:clooddddolc:;,'...',::;:looddddddddoolc::;;,,,'''..   ...';:::,..      ",
        "  .';c:,.    .          ....';;:clodxxdolllooooodxxxkOOOOkkkxxddolc:;;,'''....        ...'coolc,.   ",
        "';cl:,..                   .....',;:lollllloxkxdooddxkxxxxxxdoolc;'..'......            ..,:codxdc,.",
        "olc:'..                 .    .......'',,,,,;cc::;;;:ccc:;:cc:::;'.........              ..,;:clddxxo",
        "cc:,..                   .        ................................ .   ...      .    ....,;;;clldxkO",
        ";:;,..                    .               .....  ..    .......        ......       .....';;;:clcloox",
        ":;;;,..               .. ....                          ....          .......     ......,::;:codddoll",
        ":;;;,'....           ........                          ...            ......    ......,:::::cldxxdc,",
        "c:;,'.........        ...   .                          ....        .........    .....,::ccc:codlc:cl",
        "c:;;,''.......        ....                             .....      ..........   ....,;;::ccclol::cllc",
        "llcc;;;''.......      .. ..                          ...  ... ..   .........    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....                                       .   .....    ........   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'...      ..      .  .                         ....  ...........   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....               ...                               .......'...  .':llc:;,'...    .';:;",
        " ..',;::;;,,'....  ..   ...                                      ......''..  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''..........                                    ...''...'''....,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....'.....                ..     ...        ...''...'','''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..'''....                     ...       ....''',,'.......'..... .............',:",
        ".        ..'..',;cllc;;;,,'..                    ...        ..'',,,'..........'',,;;............'',;",
        "...           .....',,,,,;,'..                    .        ..,;;;,...........;c;,;,'......',',,',,;:",
        ".....             ............                           ..,;;;'............,;;'......',;;;;,;:;;;;:",
        "........              ......                           ...,:;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"
    ]
    const c_d = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOOO00KKXXXXXXNNNWWWWWNNNNNNXXXKKK00OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXNNNNWWWWWWWWWWWWWWWNNNXXKK00OOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKXXXNNNWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOO00KKXXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOkkkkkkkkxo,.            ",
        "            .cxxxxxkkkOO0KKKXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKK00OOkkkkkkkxo;.           ",
        "           .cxkkkkkkkO00KKKKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkxkxo,.          ",
        "          .;dkkkkkkOO0000KKXNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNNXXXK0OOkkxxxxxl'          ",
        "          .cxkOOOOO000000KKKK000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNXXK00Okkxxxxdc.         ",
        "          .lxkO000KKKK0OxxddolclodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNNXXKK00Okxxxxdo;.        ",
        "          'okOO0KKXXKOxddxxxkkxdoodxk0KXXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KKK0Okkxxddoc.        ",
        "          ,okO0KKXXX0OO0KKKXXNXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO00OOOkkO0K0Okxddooc'        ",
        "          ,dkO0KXXNXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          ;dO00KXNNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxxdolc.        ",
        "         .;dO0KKXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .:xO0KKXXXXKK0Oxdoooc,',;cxdllx0XKxdk0XNNWWWNX0kdxO0kdodxxkO0OOOOOkO0K0000Okxddol:.        ",
        "        .;okO0KKXNNXXKOxo::xk:..;,,kKkolx0NX000KXNNNXXXKKKXKklldd;.,;',odooodkO00O0Okxddol,.        ",
        "        .:dkO0KKXNNNNNXXK0xdxoclddd0XXKKKKXK00KKXXXXXKK0KXXKOO0XOc;lc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNNNNXK000KXXXXXXK0OO0KXXNXXXK00OxxkxddkO0KXXKK0kxddoc,.        ",
        "       .,lxkO00KXNNNWWWWWWWWWWWWWWWWWWWNXKK00KKKXXXKKK00OO0KXXNNNWWWNXXK0O0KXNNNXXK0Oxxdool;.       ",
        "       .cxkOO00KXNNNWWWWWWMMMWWWWWWWNNXKKKKK0KKXXXXXKKK00OOO0KNNWWWWWWWWWWWWWNNNNXK0Okxddl,..       ",
        "       .lxkOO0KXXNNNWWWWMMMMMWWWWNNXKKKKKKKKKKKXNNNNXXKK000OO0KXNNWWWWWMMMMMWWWWNNX0Okddl,.'.       ",
        "       'lxkOO0KXXNNNWWWWWWWWWWNNXXK0O0000000000KXNNNXKK000000000KXNNWWWWMMMMWWWWNXK0Oxxdxo:;.       ",
        "       .lkkkOO0KXXXXNNNNNNNNNXXKKKOxoddddddddxkO00K00OkkkO0000OOO0KXXNNWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkOO00KKKKKKKXXXKKKKK00Odc;,,,,',,;codddddocc:cllooddk0KKKKXNNWWWWNNNXXKOkxdddxd:.       ",
        "       .:dxxxxkkkkkOOOOO00000OOOOkkxdl:;;;;;;,,;::::::;,',,',;coxO0000KKXXXXXXXKK00kxddxOko,        ",
        "       .:dxddxddxdddxxxxkkkkxxxkkkkkxkxxxxkkkxdolllodxxdoolllodxxkOOOOO00KKK000OOOkxdddk0x:.        ",
        "       ,oxxdddddddddddxxxxdooddxxkkkkOOOOOO00KKKKKKKK00OOOkkkkkkkkkkOOkkOOOOOOkkxxxdoooxxc.         ",
        "      .,llodooooddddddxkxolooodxkkOOkkkkkOOO00KXXXXXXK000OOOkOOOkkkkkkkxxkkkxxxxddoolodxo,.         ",
        "       ..':ooooooddxxxkkxddooodddddddooddddxkkOO000000OOkxxxkkkkkkxxxxxxxxxxdoooooollodo:.          ",
        "         .,looooodxxxkkOkxxdolc;;;:cclooodddxxkkkxxxxxxdoollooodddxxdddddxxddoooollllodo:.          ",
        "          .coooooddxxkkOOkkkdoc'.,lkOKXKKXNXXWWWNXKXNNXK00kkxlc:::codddddxkxxddolllllccc,.          ",
        "          .:loooooodddxkOOOOkkkdlclokKK0000KNWWWNXXNWWWNX00XN0xl,.':odxxxkkxxddoolllc,...           ",
        "          .,cloooolloodxkkkOOOkkkOkxO0KXNXXNNNNWXKXNWNNNXXXXKko:::lodxkkkOkxdooolllc,.              ",
        "           .cllllllllllodxkOO0OkkOOOOO0KXXNWWWWWWWWWWWWMMWWNX0kxkOkkkOOkkkxdoooolll:.               ",
        "           .;ccccllllcclodxkOOOOkkkkOOO0KXXXNNNNWWWWNNNNNXKK0OkkkkkOOOkkkxooooolllc,.               ",
        "            ,cc:::cccccclodxkOOOOkxdddxkOKXXXNNNNNNNNNNNNXK0OkxxxkOOOkkxxdolllllll:.                ",
        "            ,c:;;;::ccccloddxkOOOkxdolllodkO0KKXXXXXXXXK0OxdddddxkkOOkkxdollllcccc,                 ",
        "           .;l:,',,;;::ccldxxkkOOOkxolc:;;:clodxxkkkkxxdolllooddxkkkkkxdollcc::;;:;...              ",
        "        .';;;,....',,,;::cloxxkkOOOkxol:;;,',,,,;;;;;;;::cccloddxxxxxxxolcc:;;,'..',;;;,..          ",
        "     .'::,'..... ....'',,;;clodkkO0Okxddolcc::::ccccc::cllooddxxkxxxdoocc::,''..   ...';:::,..      ",
        "  .';c:,.    ..   .....'''',,;coxkO0Okxxdddooooooxkkxxxkkkkkkkkkxxdoc::;;,,'...       ...'coolc,.   ",
        "';cl:,..      ..  ........''.',:coxkOkxxddddxOkxkkkOOO0OOkkkkkkxdol:;;,'''....          ..,:codxdc,.",
        "olc:'..           ............'',;:loodooooddddddddddxxdooodddoc::,''''',,'...          ..,;:cldxxxo",
        "c::,..             ...''...'......',;,;;:cllccclccc:::cc::::::;,''....',,'....  .    ....,;;;clldxkO",
        ";:;,..             ...,,..''............',;;;::;,,'''',,,,,''','......'''''...     .....';;;:clcloox",
        ":;;;,..            ...','''..............'...'','.......''''........''.''''............,::;:codddoll",
        ":;;;,'....         ..',''''......................... ....','........''',,,'...........,:::::cldxxdc,",
        "c:;,'.........     ...,''.''..............................','...'..''''',,'... ......,:cccc:codlc:cl",
        "c:;;,''........   .........''...............  .........''...'..''...'''','..   ....,;;::ccclol::cllc",
        "llcc;;;''.......  ....''....................  .....  ...'....''''..''''''''.    ..',;;;:ccc::::ccccl",
        "lodolcc::;''.... ................'.................... ............'''''''..   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'...........'.............................  ............,,,,''..  ..,:lolcc:::;,...,,,,;",
        "',,;::::::;,..... .....'''............................  ...........',,'','..  .'cllc:;,'...    .';:;",
        " ..',;::;;,,'..........''''......................................',,,,'''..  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''....''''''.................'''''...',''.........',;,''''''...,:c;'..       .,coooocc",
        "    .';;;;;,,,,'....',,,,,'.............'''',,,'''',,''''.......',,''',,,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;''',,,,'...    .....'''''''''''''''''... ...',,,,,'.......'..... .............',:",
        ".        ..'..',;:llc;;;;,,...       ....''''..''''''''...  ..',,;,'..........'',,;;............'',;",
        "...           .....',,,,,,,'..         .....................',,;;'...........;c;,;,'......',',,',,;:",
        ".....             ............ .         ..................,;;,'............,;;'......',;;;;,;:;;;;:",
        "........              ......               ...............,:;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                   ..........,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"
    ]
    const o = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOOO00KKXXXXXXNNNNWWWWNNNNNNXXXKK000OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXNNNNWWWWWWWWWWWWWWWNNNXXKK00OOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKXXXNNWWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOO00KKXXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK00OOOkkkkkkkxo,.            ",
        "            .cxxxxxkkkOO0KKKXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKK00OOkkkkkkkxo,.           ",
        "           .cxkkkkkkkO00KKKKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXXK00OOkkkxxkxo,.          ",
        "          .;dkkkkkkOO0000KKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNXXXK0OOkkxxxxxl'          ",
        "          .:xkkOOOO000000KKK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNXXK00Okkxxxxdc.         ",
        "          .lxkOO00KKKK0OkxddolllodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNXXXKK00Okxxxxdo;.        ",
        "          'lxOO00KKXK0xddxxxkkxdoodxk0KXXNNWWMMMMMMMMMMMMMMWWNXK0OxddddxkO0000KKK0Okkxxddoc.        ",
        "          'okO0KKXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO00OOOkkO0K0Okxddooc'        ",
        "          'ok00KXXNXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          ,dO0KXXNNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxxdolc.        ",
        "          ,dO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .:xO0KXXXXXKK0Oxdoooc,',;cxdllx0XKkdk0XNWWWWNX0kdxO0kdodxxkOOOOOOOOO000000Okxddol:.        ",
        "        .;dkO0KXXNNXXKOxo::xk:..;,,kKkolx0NX00KKXNNNNXXKKKXKxlldd;.,;',odooodk000O0Okxddol,.        ",
        "        .cdOO0KKXNNNNNXXK0kdxoclddd0XXKKKKXK00KXXNNXXKK0KXXKOO0XOc;lc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNWWNXK00KKXXXXXXK0000KXNNNXXK00OxxkxddkO0KXXKK0kxddoc,.        ",
        "       .,lxkO00KXNNNWWWWWWWWWWWWWWWWWWWNXKKKKKKXXXXXKK00OO0KXNNNNWWWNXXK0O0KXNNNXXK0Oxddool;.       ",
        "       .cxkOO0KKXNNNWWWWWWMWMWWWWWWWWNNXKKKKKKKXXXXXXKK00OO0KXNNNWWWWWMWWWWWWNNNNXK0Oxdddl,..       ",
        "       .lxkOO0KXXNNNWWWWMMMMWWWWWWWNNXK00KKKKKKXNNNNNXKK000O0KXNNNWWWWMMMMMMWWWNNNX0Oxddo,.'.       ",
        "       .lxkOO0KXXNNNWWWWWWWWWWWWNNNXXK000KKK0O0KKXXXXK00000000KXNNNWWWWWWMMWWWWWNXX0Oxddxo:;.       ",
        "       .lkkkO00KXXNNNNNNNWWWNNNNNNXX0OkxddollodkOO00OkxxxkOO0O0KXNNNNWWWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkOO0KKKXXXXXXXXNNNNNXXX0koc:;'....,coddddl;''',:odxOXXNNNNNNWWWNNNNNXX0Okxddddd:.       ",
        "       .:dxxxkkOO000000KKKKKXXXXXXKOxdlccccccc:;:::ccc:;;,,,;cokKXXXNNNNNXXXXXXKK0OkxddxOko,        ",
        "       .cdxdxxkkkkOOOO000000KKXXK0000OOOOOOO000OkxkkkOOOkkkxddxO0KKXXXXXKKK00000OOkxdddk0x:.        ",
        "       ,oxxddxxxxkkkkkOOOO000KK00000000000000KKKKXXKKK000OOOO000000KKKKK0000OOOkkxddoodxxc.         ",
        "      .,llodddddxxxxkkkkOOOO00000000OOOO0000KKKKKKKKKKK000OOOOOOO0000000OOOOkkkxxdoolldxl,.         ",
        "       ..':ooooodddxxxkkkOOOO0000OOOOO000000000KKKKKKK000OOOOOOOOOOOOOOOkkkkxxxddolllodo:.          ",
        "         .,looooooddddxkkkOOOOOOOkOOOOOOkkkkkkkOO0000OkkkkkkkOOkkkOOOOkkkkxxxdooollllodo:.          ",
        "          .cooooooooddxxkkOOOOOOkkkOkkxddolcloooooddooolllloxxkkOkkkOkkxxddddooolllllccc,.          ",
        "          .;looooooodddxxkkOOOkkkkkxdddl::;,,:cc:;cclc:'',:cldxxkkkkkkkxxddooooollllc,...           ",
        "           ,cllooooodddxxkkkOkkkkkxxdoll:,................,:cldxxkkkkkxxxdooooollllc,.              ",
        "           .:lllooooodddxkkkkkkkkxxxxkk0Okdoc;'........,:oxkkxdxdxxxxxxxddoooooolll:.               ",
        "           .,ccccllooooodxxkkkkkkkkxkO000KKKK0koc:::clx0KKKKK0Okdxkxxxxddoooooollll,.               ",
        "            ':c::ccllllooddxxxxxxkkxxxkkOO0KXXXKKKKKKKXXXXK0OOkxxkxxxddooooooollll:.                ",
        "            '::;;::cclllloodddxxxxkkxdddddxO00KKKKXKKKKK0Okxxdddxdddddoooooolllclc,.                ",
        "           .;l;',;;:cccllllllooddddxxdolllllodxkOOOOOOkkxdoooooddoooooollllllcc:cc;'..              ",
        "        .';;;,....,;:ccccccccccloodddddoc:;,,,,,,;;;;;;:::cloodoooolllllllllcc:,''',;;;,..          ",
        "     .'::;'....  ..';::ccc:::::ccloooooolc:;,,''',,''',;:clooooolllccccllllc:;,..  ...';:::,..      ",
        "  .';c:,.    .     .';;;:cc::::cccllllllllcc::;,,;;::::clodddoolccccccccllc:,...      ...'coolc,.   ",
        "';cl:,..      .     .',,;::::::ccllllllllccc:::::ccllllodddddollcccc::ccc:;'..          ..,:codxdc,.",
        "olc:'..             ...',;;;;,;;:ccllloolllllllclllooddxdddddoolc:;::;;:;,....          ..,;:clddxxo",
        "cc:,..             ....'''''.''',;;cllodollllollllllooddddxdoolc:,,,,,,,'....   .    ....,;;;clldxkO",
        ";:;,..              ....''''..'''',,;:clllc:clllcccclllllllollc;,'''.',,'....      .....';;;:clcloox",
        ":;;;,..             ....'...'.......',,,;;;:::::::::;::;,;;;;,,'....',,''....   .......,::;:codddoll",
        ":;;;,'....           ..''...'............'',,,,,,,,,'...''',,'......','..'..   .......,:::::cldxxdc,",
        "c:;,'.........      ...',..''...............'''''.......'''...........'''''.    .....,::ccc:codlc:cl",
        "c:;;,''.......     ...''''.'.............'.....''........''........'''','''.   ....,;;::ccclol::cllc",
        "llcc;;;''.......   ...','.''........ ....................',,......'',,,','..    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....  ....''...''................ ..........'..',..''...',''''..   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'.... ..........''............... ...  .....'...'..''....'''''..  ..,:lolcc:::;,...,,,,;",
        "',,;::::::;,..... .....''.................... ................'''...'''','..  .'cllc:;,'...    .';:;",
        " ..',;::;;,,'....................''...........................'....',',,,'.  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''.............................. .......   ..........',,,,''...,:c;'..       .,coooocc",
        "    .';;;;;,,,,'....''''..............................   ..........',,,,,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;''',,,'......................................'',,,'.......'..... .............',:",
        ".        ..'..',;:llc:;;;;'...    ..................''..... ...',;,'..........'',,;;............'',;",
        "...           .....',,,,,;,'..      ..................... ....,;;'...........;c;,;,'......',',,',,;:",
        ".....             ...............       ................  ..',,'............,;;'......',;;;;,;:;;;;:",
        "........              ......                  ....  ......';,............'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...';;.........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                        ..','..................',;;;;;,,;;;;;:c:c:::;"
    ]
    const l_d_th = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOOO00KKXXXXXXNNNWWWWWNNNNNNXXXKKK0OOOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkOOOOO00KKXXXNNNNWWWWWWWWWWWWWWWNNNXXKK00OOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO000KKKXXNNNWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOOO0KKXXXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK00OOOkkkkkkkxo,.            ",
        "            .cxxxxxxkkOO00KKXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKK00OOkkkkkkkxo;.           ",
        "           .cxkkxkkkkOO00KKKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkxkxo,.          ",
        "          .;dkkkkkkOOO0O0KKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXKK0OOkkxxxxxl'          ",
        "          .cxkkkOOOO00000KKK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNXKK0OOkxxxxxdc.         ",
        "          .lxkOOO0000K0OxxddolclodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNNXKKK00Okxxxxdo;.        ",
        "          'lxOO00KKKKOxddxxxkkxdoodxk0KXXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KK00Okkxdddoc.        ",
        "          'okO0KKXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxOO0OOOkkO000Okxddooc'        ",
        "          'okO0KXXXXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          ,oO00KXNNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxxdolc.        ",
        "          ,dO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .;dO0KKXXXKKK0Oxdoooc,',;cxdllx0XKkdk0XNWWWWNX0kdxO0kdodxxkOOOOOOOkO000000Okxddol:.        ",
        "        .;okO0KKXNNXXKOxo::xk:..;,,kKkolx0NX000KXNNNXXXKKKKKxlldd;.,;',odooodk00OOOOkxddol,.        ",
        "        .:dkO0KKXXNNNNXXK0xdxoclddd0XXKKKKXK000KXXXXXK00KXXKOO0XOc;lc.:OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNNNNXK000KXXXXKK0OOO0KXXNNXXK00OxxkxddkO0KXXKK0kxddoc,.        ",
        "       .,lxkOO0KXXNWWWWWWWWWWWWWWWWWWWNNXKK00KKKKKKKK0OOkO0KXXNNNNWWNXKK0O0KXNNNXXK0kxddodl;.       ",
        "       .cxkkO00KXNNWWWWWWMMWWWWWWWWWWNXK00000KKKKKKKK00OOkO0KXXNNWWWWWWWWWWWWNNNNXK0kxdddl,..       ",
        "       .lxkOO00KXNNNWWWWWMMWWWWWWWNNXK0000000KKXXXXXKK00OOkO0KXXNNNWWWWMMMMWWWWWNXK0Oxddo,.'.       ",
        "       'lxkOO00KXNNNWWWWWWWWWWWNNNXK0000000000KXXNNXXK0000OOO0KXXNNNNWWWWWWWWWWWNXK0Oxddxo:;.       ",
        "       .lxkkkO0KXXNNNNNNNNNNNNNXXK0OkkkkxxxxxkO00KK0OkkO0000OO0KXXNNNNNWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkkOO0KKKKKKKKXXKKKKK00kdlc:;,''';codxxxxdlcclodxkkk0KXXXNNNNNNNNNNNXXK0Oxxddddd:.       ",
        "       .:dxxxxkkkOOOO000000000000Oxo:'........,;::::;'....',:cok0KKXXXXXXXXXXXKKK0OkxddxOko,        ",
        "       .cdxddxxxxxxkkkkOOOO000OOOkkxdollloodol:;;::clolcc:,,,:oxO00KKKKKK000000OOkxxdodk0x:.        ",
        "       ,oxxdddddddxxxxkkkkkOOOOOOOkkkkkkkkOO0000OO0OOOOOkxxdxxkkO000KK000OOOkkkkxddooodxxc.         ",
        "      .,llodooodddddddxxxkkkkOOOOOkkkkOOOOO000000KKKK00OOkkkkkkOOOOO00OOOOkkkxxddoollldxl,.         ",
        "       ..':ooloooodddddxxxxkkkkkkkkOOOkkkkkkkOO0000K00OOOkkkkkkkkOOOOOOkkkkxxxdoollllodo:.          ",
        "          ,coollooodddxxxxkkkkkkkkkkxdoollodddxxkkkkxdddddxxkkkkkkOOOOkkxxxxddoolllclodo:.          ",
        "          .:oolllooddddxxxkkkkxxxxdol:;;;clloodddddddolc::clodxkkkkkkkkxxxdddoollllllccc,.          ",
        "          .;lllloooddddxxxkkxxxxxoolc:,';lokKKKKOOKKXK0xc,,;:loxkkkkkkxxxdddooolllllc,...           ",
        "           'clllllooddxxxxxxxxxxdoc::,. ...:dkOOdxkO0Ox:...,,:ldkkkkkxxxddddoolllllc,.              ",
        "           .:llllllooddxxxxxxxddddoll;;c;,;:lddocclol:,.....',:oxkkxxxxxdddoollllll:.               ",
        "           .,ccccccllooddddddddddxO000KKKKXXXXNK0KXXKOkxxkkxxodxdxxdddxdddoollllllc'                ",
        "            '::::::cclloooooodddddxkO0KKKKKXNWWWNWWWNXXKK0OOOOkxxxddddddoollllllcc:.                ",
        "            '::;;;;:cccclllllooddoodxOKXXXXXXXKKXXXXXXXXK0kkkxxxxddooooollllcccccc'                 ",
        "           .;l;',,,;:::::cccllllllccldk0XXXXXKKKXXXXXXXX0kdooodddooooolllcccc:::::;...              ",
        "        .';;;,....',,;::::::ccllccc:,,:oxO000OOO0000K0Oxolccloooooolllccc::::;;'..',;;;,..          ",
        "     .'::;'....   ..'',;;::ccclllcc:,'..,;cloooddooolc;,,;:clllooollccc::::;;,'.   ...';:::,..      ",
        "  .';c:,.    .     ....',;::clllllcc:,...  ............,:ccllooolllcc:::;;;,'..       ...'coolc,.   ",
        "';cl:,..      .      ....'',;:clllllc:;'....   .....,:clllloodoollc::;,,,,'..           ..,:codxdc,.",
        "olc:'..               .......',;:cloolc:;'.''''';:cldxddddxdddolc:,,,''''....           ..,;:clddxxo",
        "cc:,..              . .........'';:loolc:;:lllc:clooddddxxxdolc:;'...........   .    ....,;;;clldxkO",
        ";:;,..             ...............',;;::;;:cc:::;:::c:::ccc::;,'.......'.....      .....';;;:clcloox",
        ":;;;,..              .........  ........',,,,,'''...''''','''..........'.....   .......,::;:codddoll",
        ":;;;,'....           .........  . .. ............  ..................''......  .......,:::::cldxxdc,",
        "c:;,'.........      ..........  . .   ..........     ...........  .......'..   ......,::ccc:codlc:cl",
        "c:;;,''.......      ..........  .     ....   ...      ..'.. ............''..   ....,;;::ccclol::cllc",
        "llcc;;;''.......    .......... ...                   ...................'...    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....    .........  .....    .           ........................   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'...     ...................            ........................   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....     ................       .....     .. ..............''...  .'cllc:;,'...    .';:;",
        " ..',;::;;,,'....  ..  ....  ......  ..       ... .      ...... .......''..  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''............ ...........      .....         ......'''''''....,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....'......    ...  .... ...........      ......'''''',,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..'''...        .......................  ...''',,''......'..... .............',:",
        ".        ..'..',;:llc;;;,,'..         ..................    ...',;,'..........'',,;;............'',;",
        "...           .....',,,,,,,'..          ...............    ..';;;,...........;c;,;,'......',',,',,;:",
        ".....             ..............                .....     .';;,'............,;;'......',;;;;,;:;;;;:",
        "........              ......                            ..,;;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...','..................',;;;;;,,;;;;;:c:c:::;"
    ]
    const m_b_p = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOOO00KKXXXXXXNNNNWWWWNNNNNNXXXKK000OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXNNNNWWWWWWWWWWWWWWWNNNXXKK00OOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO000KKKXXNNNWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOOO0KKXXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK00OOOkkkkkkkko,.            ",
        "            .cxxxxxkkkkO00KKXXXXNNNWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKK00OOkkkkkkkxo,.           ",
        "           .cxkkkkkkkOO00KKKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkkkxo,.          ",
        "          .;dkkkkkkkOOOO00KXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXKK0OOkkxxxxxl'          ",
        "          .:xkkOOOOO0OO000KK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNXKK0OOkxxxxxdc.         ",
        "          .lxkOOO000000OxxddolllodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNXXKKK00Okxxxxdo;.        ",
        "          'lkOO00KKKKOxddxxxkkxdoodxk0KKXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KK00Okkxxddo:.        ",
        "          'okO0KKXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO00OOOkkO000Okxddooc'        ",
        "          'okO0KXXXXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          'oO0KKXXXXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxddolc.        ",
        "          'oO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .;dO0KXXXXXKK0Oxdoooc,',;cxdllx0XKxdk0XNNWWWNX0kdxO0kdodxxkOOOOOOOOO000000Okxddol:.        ",
        "        .;okO0KXXXNNXKOxo::xk:..;,,kKkolx0NX000KXNNNNXXKKKXKxlldd;.,;',odooodk00OOOOkxddol,.        ",
        "        .:dkO0KKXXNNNNXXK0kdxoclddd0XXKK0KXK00KKXXXXXK00KKXKOO0XOc;lc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNNNNXK000KXXXXXKK0OO0KXNNNXXK00OxxkxddkO0KXXKK0kxddoc,.        ",
        "       .,lxkOO0KXXNNWWWWWWWWWWWWWWWWWWNNXKK00KKKKKKKK00OOO0KXXNNWWWWNXKK0O0KXNNNXXK0Oxddodl;.       ",
        "       .cxkOO00KXNNNWWWWWWMMMWWWWWWWWNXK00000KKKKKKKKK0OOOO0KXXNNWWWWWWWWWWWWNNNNXK0Oxdddl,..       ",
        "       .lxkOO0KKXNNNWWWWMMMWWWWWWWNNNK0000000KKXXXXXKK000OOO0KXNNNNWWWWMMMMMWWWWNXK0Oxddo,.'.       ",
        "       .lxkOO0KKXNNNWWWWWWWWWWWNNNNXK0000K0000KXXNNXXK00000OO0KXNNNNWWWWWWWWWWWWNXX0Oxddxo:;.       ",
        "       .lxkkOO0KXXXXNNNNNNNNNNNNNXXK0kkkkkkxxkO00KK0OkkO0000OOKXNNNNNNWWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkOO00KKKKKKKXXXXXXXXXXKOxol:,...':oxkkkxdlc:codkkkOKXXNNNNNNNNNNNNNNXK0Okxddddd:.       ",
        "       .:dxxxkkOOOOOO00000KKKKXXK0Oxoc;,,'''.';cllll:'.....;cox0KXXXXXXXXXXXXKKKK0OkxddxOko,        ",
        "       .cdxdxxkkkkkkkkkOOO000KK00OOkxdddxkOOkdlccllloxxdol:;:cdO0KKXXXKKKK00000OOkkxdddk0x:.        ",
        "       ,oxxddxxxxxxxxxkkkkOOO00OOOO00000000KKKK00000KKK00OkxxxkO000KKKK000OOOkkkkxddoooxxl'         ",
        "      .,llodddddddddddxxxxkkOOOOOO00000000KKXXXXNNXXXKKKK00000000OO0000OOOkkkxxxxdoolldxo,.         ",
        "       ..':ooodooooodddxxxkkkkkkOOOOO00000KKXXNNNNNNXXKK0000000OOOOOOOOOkkkkxxxddoollodo:.          ",
        "         .;loooolllloddxxxxxdooxkkkkOO00000KXNNNNNNNNXKK000OOOOOkkkkkkkkkxxxxxddoolllodo:.          ",
        "          'cooolllcloddxxxdollldxkkkOO000000KXXXXXXXXKKKK0000Okxxxxxxxxxxxdddddoollllccc,.          ",
        "          .:loooooooddxxxdool::clooddxxxxxxxkkO0000OOOkkkOOOOOkxxdooddddddddddoollllc,...           ",
        "          .,cloooooodddxxxdoc;,,,,',:llooddxxxkOOOOOkkxxddddoolllllllooddddddooolllc;.              ",
        "           .:llloooooooddxddol::ccclooodxdoolllodddddoooooolc:;::::cooodxddddoollll:.               ",
        "           .;cccllollccloddxxxxdddxkkxxxkOkkxdollloodxxxkkxxxxxdolldxddxxoooolllllc,.               ",
        "            ':::::ccc::;clodxkkkkkkkkkkkkkOOO000OOO00OOOOOOkkkxxxxkkxxxdolllllllll:.                ",
        "            '::;;;;:::;,,:coxxkkkkxxxxxxxdoodddddxxxkkkOOOOOkkxxkkkxxddlcccccccccc,.                ",
        "           .;l;'',,,;;;,,;:codxxxxxdoollc::::::::ccloodxxxxxxxxxxxxxdolc:cccc::::c;'..              ",
        "        .';;;,......',,;;;:clooddddoolcc:::;;,;;;:cccclooddddddddxxdol:::::::;;,'.',;;;,..          ",
        "     .'::;'....   ....',;;:clloooddoollc:::;;,;::clcccloodddddddddoolc:::;;;;,'..  ...';:::,..      ",
        "  .';c:,.    .      ....,,;::clloodddollccllcccloodooddddddddddddoolc:::;;,,'..       ...'coolc,.   ",
        "';cl:,..              ...''',,;::cloooooooddoddddddxxxkxxxxxddddolc:;;,,,,'..           ..,:codxdc,.",
        "olc:'..               .........'',;:ccccllcldxdolllodxddoddddoolc:,'',''.....           ..,;:clddxxo",
        "cc:,..              ...............'',,;;;;::cccc:::clc::::c:::;,'..........         ....,;;;clldxkO",
        ";:;,..               .......... .........',,'',,,,,,',,'''''''.........''....      .....';;;:clcloox",
        ":;;;,..              ................ ................................'......   .......,::;:codddoll",
        ":;;;,'....           .......... ...   ...........   ............. ..........   .......,:::::cldxxdc,",
        "c:;,'.........      .............      ....   ...      ...... ............'.   ......,::ccc:codlc:cl",
        "c:;;,''.......      ..............      ..     ..     ....''. ......''......   ....,;;::ccclol::cllc",
        "llcc;;;''.......    .......... ......   . .          ......'...........''...    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....    .................. .             ...................'...   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'....    ................. .      ...      .. ..............''..  ..,:lolcc:::;,...,,,,;",
        "',,;::::::;,....      ......  ...... ...       ...        ............'',,..  .'cllc:;,'...    .';:;",
        " ..',;::;;,,'....  .. ......  .........         ...         .... ..'',,','.  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''...............  .   ....   .    ...        ......''''',,'...,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....'.......   ....... ................. ... ..',,,'',,,,'';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..''''...     ........................ .....',,,,,''.....'..... .............',:",
        ".        ..'..',;:llc;;;,,'..         ....................  ...',;,'..........'',,;;............'',;",
        "...           .....',,,,,;,'..          ................    .',;;,..'........;c;,;,'......',',,',,;:",
        ".....             ............                .........   ..,;;'............,;;'......',;;;;,;:;;;;:",
        "........              ......                        .   ..';;'...........'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                           ..';;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                        ..','...................,;;;;;,,;;;;;:c:c:::;"

    ]
    const w_q = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkOOOO00KKXXXXXXNNNNWWWWNNNNNNXXXKKK00OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXXNNNWWWWWWWWWWWWWWWNNNXXKK0OOOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKKXXNNNWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOOO0KKXXXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkxo,.            ",
        "            .cxxxxxkkkkO00KKXXXXNNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWWWNNNXXKK00OOkkkkkkkxo;.           ",
        "           .cxkkxkkkkOO00KKKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkxkxo,.          ",
        "          .;dkkkkkkkOOOO0KKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXKK0OOkkxxxxxl'          ",
        "          .cxkkkOOOO0OO000KK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNXXXK00Okkxxxxdc.         ",
        "          .lxkOOO000000kxxddolllodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNXXKKK00Okxxxxdo;.        ",
        "          'lxOO00KKKKOxddxxxkkxdoodxk0KKXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KKK0Okkxxddoc.        ",
        "          'okO0KKXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO0OOOOkkO000Okxxdooc'        ",
        "          'okO0KXXXXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          ,ok0KKXXNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxddolc.        ",
        "          ,oO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .;dO0KXXXXKKK0Oxdoooc,',;cxdllx0XKxdk0XNNWWWNX0kdxO0kdodxxkOOOOOOOkO000000Okxddol:.        ",
        "        .;okO0KXXXXXXKOxo::xk:..;,,kKkolx0NK000KXNNNXXXKKKXKxlldd;.,;',odooodk00OOOOkxddol,.        ",
        "        .:dkO0KKXXNNNNXXK0kdxoclddd0XXKK0KXK00KXXXXXXK00KKXKOO0XOc;cc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNNNNXK00KKXXXXXKK0OO0KXXNNXXK00OxxkxddkO0KXXKK0kxddoc,.        ",
        "       .,lxkOO0KXXNNWWWWWWWWWWWWWWWWWWNNXKK0KKKKKKKKK00OOO0KXXNNNWWWNXKK0O0KXNNNXXK0kxddodl;.       ",
        "       .cdkOO00KXNNNWWWWWMMWWWWWWWWWNNXKKK000KKXXXXKKK00OOO0KXXNNWWWWWWWWWWWNNNNNXK0kxdddl,..       ",
        "       .lxkOO0KKXNNNWWWWMMMWWWWWWWNNXKK0KK000KXXNNNXKK000OOO0KXNNNNWWWWMMMMWWWWNNXK0Oxddo,...       ",
        "       'lxkOO0KKXNNNWWWWWWWWWWWNNNXX000000OkkO0KKKKK0OOO0000O0KXNNNNNWWWWWMWWWWWNXK0Oxddxo:;.       ",
        "       .lxkkOO0KXXXNNNNNNNNNNNNNNXKOxdolc:;;coxkkkkkxoodxkOOOO0XXNNNNNNWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkkO00KKKKKKKKKKKKKXXXKOxl;,......':ccllc;'...';loox0XXXNNXXXNNNNNNNNXK0Oxdddddd:.       ",
        "       .:dxxxxkkkOOOOO0000000KKKK0Oxo:;;:cccc:;,;;;:::;,'...,:dOKKKXXXKKKKKKXKKK00OkxddxOko,        ",
        "       .cxxddxxxxxxkkkkOOOO000000000OkkxxkkOOOOkkkkkkkkxdlccldxOKKKXXK0000OOOOOOkkxxdddk0x:.        ",
        "       ,oxxddddddxxxxkkkkOOO000000OOOkkkkOO0000KK00000OkkkkkkOO000KKKK00OOOkkkkxxddooodxxc.         ",
        "      .;loodddddddxxxxxkkkkOO000OOkkkOOOOOOO0000KKKK000OOOkkkkkOO000000OOkkkxxddooollldxo,.         ",
        "       ..':oooooddxxxxkkkkkOOOOOkkkOOOkkxxkkxkkOOOOOkxxxxkkkkkkkkO000OOkkkxxxddoollllodo:.          ",
        "         .;loooooddxxxxxkkkkOkkkkkkkxxddlc:llloooooolccccldxkkkkkkOOOOkkkxxxddoolllllodo:.          ",
        "         .,looooodddxxxxkkkkkkkxxxddddool:,:loddlodddoc;;clodxxkkkkkkkkxxxxxddoolllllccc,.          ",
        "          .:oooooodddxxxxxkkxxxxxdolcldkOOxxkkxl;codkOkddxdooxxxOOkkkxxxxxxdddoollllc,...           ",
        "          .;loooooodddxxxxxxxddddodddxO0KKXK0Odc;:cldOKKKKKOxdddxxxxxxxxxxddooollllc,.              ",
        "           'clllooooodddxxxddddoodddkkkkOKNNNXK000KKKXXXX0OOOkxooddddxxxdddooolllll:.               ",
        "           .;cccllloooooddddooooooooooddxkO0KK00KKKKKXXK0kxkxdooddddddddooolllllllc,.               ",
        "            ':cccclllllllloollooloolc::ccodxkkOOOOOOOOOxdooolloooooodooollllllllll:.                ",
        "            'c:;::cccccccccccllllcccc:;,'',;clooooddolc:;:::clllllllllllcccllccccc,.                ",
        "           .;l;',;;::ccc::cc::cclcccc:;'................',::clllllllccccccccc::::c;'..              ",
        "        .';;;,....',;;;::::cccccllllc:;,'.....   ......,;:cclllllllccccc::::::;,'.',;;;,..          ",
        "     .'::;'....   ..''',;;:::cllooooolcc:,,'......'',;ccllooollllccc:::::::;;,'.   ...';:::,..      ",
        "  .';c:,.    .      ....'',,;::cllooddolllllcc:cllloxxxxxxxdooollcc:::;;;;,'...       ...'coolc,.   ",
        "';cl:,..      .       ........',;:cldddolloodxddddxxkkkkkkkxdool:;,',,''''...           ..,:codxdc,.",
        "olc:'..               ..........',;:ccllc:cldoollllloooooddollc:;'..'........           ..,;:clddxxo",
        "cc:,..              ...............'',,,,;;;;;;;;,,,;;,,;;;;,;,'.......'....         ....,;;;clldxkO",
        ";:;,..              ........... ..........''''.........'''.............'.....      .....';;;:clcloox",
        ":;;;,..              .........  . ...............     ...............'.......   .......,::;:codddoll",
        ":;;;,'....           ......... ...     .........     ...... ....  ..........   .......,:::::cldxxdc,",
        "c:;,'.........      ...'...... ..      ....   ...   ....'................'..    .....,::ccc:codlc:cl",
        "c:;;,''.......     ...............              .   ....................''..   ....,;;::ccclol::cllc",
        "llcc;;;''.......    .......... ......  ..           ......'............'''..    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....  .......................           ...................'....   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'.... .................... .     ....     .. ..............''...   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....  ..........  ......  .       ....       .........''''',,'..  .'cllc:;,'...    .';:;",
        " ..',;::;;,,''...  .....................  .    ...         ......'',,,,,,'.  .,cc;,'...      ...,;;;",
        "   ..,;,,;:;,,,'............................... .....      .....',,'',,,''...,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....''.......................................',;;,',,,,,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'.'''''....    ............................',;,,,,,'......''.... .............',:",
        ".        ..'..',;:llc;;;,,,...      ........................',,;;;,'..........'',,;;............'',;",
        "...           .....',,,,,;,'..         .....................,;::;,...........;c;,;,'......',',,',,;:",
        ".....             ............            ................';::;,............,;;'......',;;;;,;:;;;;:",
        "........              ......                .............,:c:'...........'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                  ..........';::'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                      ...',,'..................',;;;;;,,;;;;;:c:c:::;"

    ]
    const u = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOO000KKXXXXXXNNNNWWWWNNNNNNXXXKKK00OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXNNNNWWWWWWWWWWWWWWWNNNXXKK00OOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKXXXNNWWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOO00KKXXXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK000OOkkkkkkkxo,.            ",
        "            .cxkxxxkkkOO0KKKXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKKK0OOkkkkkkkxo,.           ",
        "           .cxkkkkkkkOO0KKKKXXNNNWWWWWWWMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNXXXKK0OOkkkkxkxo,.          ",
        "          .;dkkkkkkOOO000KKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNNXXXK00Okkkxxxxl'          ",
        "          .cxkkOOOO00O0000KK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNXXXK00Okkxxxxdc.         ",
        "          .lxkO00000000kxxddolllodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNXXXKK00Okkxxxdo;.        ",
        "          'lxOO00KKKKOxddxxxkkxdoodxk0KKXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KKK00Okxxddoc.        ",
        "          'okO0KKXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO0OOOOkkO0K0Okxxdooc'        ",
        "          'okO0KXXXXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          'oO0KXXNNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxxdolc.        ",
        "          ,oO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .;dO0KXXXXKKK0Oxdoooc,',;cxdllxKXKxdk0XNWWWWNX0kdxO0kdodxxkOOOOOOOOO000000OOxddol:.        ",
        "        .;okO0KXXNNXXKOxo::xk:..;,,kKkolx0NX000KXNNNNXXKKKXKxlldd;.,;',odooodk00000OOxddol,.        ",
        "        .:dk00KKXXNNNNXXK0kdxoclddd0XXKKKKXK00KKXNXXXKK0KXXKOO0XOc;lc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNWNNXK00KKXXXXXXK0000KXNNNXXK00OxxkxddkO0KXXXK0kxxdoc,.        ",
        "       .,lxOO00KXXNNWWWWWWWWWWWWWWWWWWWNXKKKKKKXXXXXKK00OO0KXNNNWWWWNXKK0O0KXNNNXXK0Oxxdodl;.       ",
        "       .cdkOO00KXNNNWWWWWMMMMMWWWWWWWNNXKKKK0KKXXXXXKKK00OO0KXNNNWWWWWWWWWWWWNNNNXK0Okxddl,..       ",
        "       .lxkOO0KXXNNNWWWWMMMMWWWWWWWNNXK00KKKKKKXNNNNXXK000OO0KXNNNWWWWMMMMMMWWWWNNX0Okxdo,.'.       ",
        "       .lxkOO0KXXNNNWWWWWWWWWWWWNNNNXK000KK0000KXXNNXK0000000KKXNNNNWWWWWMMWWWWWNNX0Okxdxo:;.       ",
        "       .lxkkOO0KXXNNNNNNNNNNNNNNNNXXKOkkxdddoxkO0000OkkkO000000XNNNNNNWWWWWWWWWWNXK0Oxxdxdoc.       ",
        "       .cxxxkOO0KKKKKKXXXXXXXXXXXXXKOdlc;....,coddxxdl:;;:cdxkkKNNNNNNNNNNNNNNNNXXKOkxddddd:.       ",
        "       .:dxxxkkOOO00000000KKKKXXXXKOxo:;;;;;;;;;;::::;,'...,:ld0XXNNNNXXXXXXXXXKK0OkxddxOko,        ",
        "       .:dxdxxkkkkkkOOOOO000KKKXKK0OOkxxxxkkkOkxddddxkxddollclxO0KXXXXXKKK000000Okkxxddk0x:.        ",
        "       ,oxxdddxxxkkkkOOOOO000KKK000000OOOOOO000KKKKK00OOOkkkkOO00KKXXKK000OOOOOkkxdddodkxc.         ",
        "      .,llodooddxxkkkkkkOOOO0000000OOOOO000000KKKKKKKK00OOOOOOO0000KK0000OOOkkkxddoolodxo,.         ",
        "       ..':ooooodxxkkkkOOOOOO000OOOOOOOOOOOOOOO000KK0OOOOOOOOOkOOO00000OOOkkkxxddoollodo:.          ",
        "          ,cooooddxxkkkkOOOOOOOOOkOOOOkxxdoodddxxkkxxddddxxkOOkkkOO0OOOOOkkkkxxdoolllodo:.          ",
        "          .:ooooodxxxkkkkOOOOOOkkkkkxxdolc::loddoodddolcclodxkkkkkOOOOkkkkkkxxddoolllccc,.          ",
        "          .;looooddxxxkkkkOOkkkkkkxdoooolc:lxO00xdkO0Oxl:clldxkkOOkOOkkkkkkxxddoolllc,...           ",
        "           'clloooddxxkkkkkkkkxxxxxxddk00kxkkO00xxO00kkdodxxddxxkOkkkkkkkxxxddoolllc,.              ",
        "           .:llloooddxxkkkkkxxxxxxxk00KKXXXK000KO0KK000KKXXK0Okxxxxxxxkkxxxdddoolll:.               ",
        "           .,ccccllooddxxxxxdddddddxkOO0KNNNXXKKKKKKKXXNNNK0OOOxddxxxxxxxddoooolllc,                ",
        "            ':c::ccllooooddooooooolclodxO0XXXXXXXXXXXNNNNK0kkxdodddddddddooooollll:.                ",
        "            '::;:::cclllllllllolllcc:;;:ldkOOOOO00000000Oxdollllllloooooolllllcccc'                 ",
        "           .;l;',,;::ccccclcccllllcc:;,''',:clodddddddoc:;;::cclllllllllllccc:::::;...              ",
        "        .';;;,....',;;:::ccllllloollc:;'................',;ccllloolllllccc::;;,'..',;;;,..          ",
        "     .'::,'....   ..''',;;:cclooddddolc:;'...........',::cllooooolllcccc::;;,'..   ...';:::,..      ",
        "  .';c:,.    .      ....'',,;:cllodddddoll:;;;;;;;:cldxxddddddddollcc:;;;,,...        ...'coolc,.   ",
        "';cl:,..      .      .......'',;;clodxxddolodxddoddxkkkkkkkkxddolc;;;;,'''..            ..,:codxdc,.",
        "olc:'..            ......'....'',,;:cclllcccoolllllloddoodxdoolc:;''''''....            ..,;:clddxxo",
        "cc:,..             ....'..'.......',,,,,;;::;;;;;;;;;::;;:::;;;,'......''...    .    ....,;;;clldxkO",
        ";:;,..             ....''.................''','........,,,'','........''''...      .....';;;:clcloox",
        ":;;;,..             ..''..''.................''........''.....'......','.'...   .......,::;:codddoll",
        ":;;;,'....          ..',''''''..........''.....'.......'''............''.''.    ......,:::::cldxxdc,",
        "c:;,'.........     ...'','........... .................',,'.......'''.''','.    .....,::ccc:codlc:cl",
        "c:;;,''.......    ....'''''............................'.','..'..'''''',,'..   ....,;;::ccclol::cllc",
        "llcc;;;''.......  ....'...'''.........................''..''.','...'''',,'..    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....  ....''....'..........................'....','.....'',,''..   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'..........''........''..........................''..'',''',,'..  ..':lolcc:::;,...,,,,;",
        "',,;::::::;,............'''......''.......... ...................',,,,,;;'..  .,cllc:;,'...    .';:;",
        " ..',;::;;,,'...........'''........................... ..........,;;;,,;,'.  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''....'''........................................',;;,,,,,,'...;:c;'..       .,coooocc",
        "    .';;;;;,,,,'....',,,''.................'''...''''.........',;;,,,,,,,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;,'',,,,,...    ..............'.............',,,,;,'.......'..... .............',:",
        ".        ..'..',;cllc::;;;,'..       ...........''''.........',,;;,'..........'',,;;............'',;",
        "...           .....',,,,,;,,..          ....................',;;;,...........;c;,;,'......',',,',,;:",
        ".....             ............            ................',;;,'............,;;'......',;;;;,;:;;;;:",
        "........              ......                 ............';:;'...........'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                        ....',;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"

    ]
    const e = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOOO00KKXXXXXXNNNWWWWWNNNNNNXXXKKK0OOOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXNNNNWWWWWWWWWWWWWWWNNNXXKK0OOOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOOO000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKKXXNNNWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOOO0KKXXXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkxo,.            ",
        "            .cxxxxxkkkkO00KKXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWWWNNNXXKK00OOkkkkkkkxo;.           ",
        "           .cxkkxkkkkOO00KKKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkxkxo,.          ",
        "          .;dkkkkkkkOO0O0KKXXNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNXXKK0OOkkxxxxxl'          ",
        "          .:xkkOOOOO0OO000KK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNXXK0OOkxxxxxdc.         ",
        "          .lxkOOO000000kxxddolclodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNXXKKK00Okxxxxdo;.        ",
        "          'lkOO00KKKKOxddxxxkkxdoodxk0KKXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KK00Okkxdddoc.        ",
        "          'okO0KKXXX0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxO0OOOOkkO000Okxddooc'        ",
        "          'ok00KXXXXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          'ok0KKXXNXX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNXXXK000Okxddolc.        ",
        "          'oO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOxlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .;dO0KXXXXKKK0Oxdoooc,',;cxdllx0XKxdk0XNWWWWNX0kdxO0kdodxxkO0OOOOOOO000000Okxddol:.        ",
        "        .;okO0KKXXXXXKOxo::xk:..;,,kKkolx0NX000KXNNNXXKKK0KKxlldd;.,;',odooodk00OOOOkxddol,.        ",
        "        .:dkO0KKXXNNNNXXK0xdxocldddOXXKK0KXK000KXXXXXK00KXXKOO0XOc;lc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNNNNXK0000KKXKKK0OOO0KKXNXXXK00OxxkxddkO0KXXK00kxddoc,.        ",
        "        ,lxkOO0KXXNNWWWWWWWWWWWWWWWWWWNNXK00000KKKKKK0OkkOO0KXNNNNWWNXKK0O0KXNNNXXK0Oxddool;.       ",
        "       .cdkOO00KXNNNWWWWWWMMMWWWWWWWWNXK000000KKKKKKK00OkkkOKXXNNNWWWWWWWWWWWNNNNXK0Oxdddl,..       ",
        "       .lxkOO00KXNNNWWWWMMMWWWWWWWNNXK00000000KKKKKKKK00OOkkO0XXNNWWWWWMMMMMWWWNNXK0Okddo,.'.       ",
        "       .lxkOO00KXNNNWWWWWWWWWWWNNXK0OO0000000KKXXNNNXKK000OOOO0KXNNNWWWWWMMMWWWNNXK0Oxxdxo:;.       ",
        "       .lkkkOO0KXXXNNNNNNNNNNXXKK0OkkOOOO0OOOO0KKXXXK00000000OO0KKXXNNWWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkOO00KKKKKKKKXXXK0000OkolllcccccloxkOOOOkxdxxkOOOOkkO00KXXNNNNNWNNNNXX0Okxdddxd:.       ",
        "       .:dxxxkkOOOOOOOOO00000OOOOkxo;'.......,:clllll:;,;;::cllok0000KKXXXXXXXKKK0OkxddxOko,        ",
        "       .:dxdxxxxxxxxxkkkkkOOOOkkkxxdoc:;;;;;;,',,;;;;;,,'''.',:oxO0OO00KKKK0000OOOkxdddk0x:.        ",
        "       ,oxxddddddddodddddxkkkxxxxxxxxxxxxkkkkkdoloodxkxxdolllodxxkkkkOOOOOOOOOkkxxxdoooxxl.         ",
        "      .,llodoooodooooodddxxxddddxxkkkOOkkOOO00KKKKKK000OOkkxxxkkkkkkkkkkkkkkxxxddddolldxo,.         ",
        "       ..':ollloooooooddxxdoooodkkkkkkkkkkkOO00KKKKKK0OOOkkkkkkkkxxxxkxxxxddddooolllllooc.          ",
        "          ,coolllooodddxxdoollodddddddddddxkkkO000000OOOkxxxxkkkkxxdxxxxxddolllllccclodo:.          ",
        "          .:oolllodddxxkkxdolc:;;;::;:cclloooodxxxxxddddollloooddxxdddddddoolllccccllccc,.          ",
        "          .;lllloooddxxkkkxxoc;...;coxkxkOOO0KK0OxkkOOOkdlcc:;;:::looodddxddoolllcll:,...           ",
        "           'cllllloodddxkkkkxddoc::ldO0KXXKXWWWWK0XNWWWNKOOOdc,'..':loddxxdddoollllc,.              ",
        "           .:lllllllllodxxxkkkxxkOkkkO0KXNWWWNWWXKNNWNWWWWNKOdc;;:clodxxkxddooollll;.               ",
        "           .,cccccccccclodxkkkkxxxkkkO00KKXXNXNNNNWNNNNNNXK0Okxxkxxxkkkkxxooooolllc'                ",
        "            '::::::::::clldxkkkkxdddxxkOKXXXXXXXXXXXXNNNXKK0kxddxxkkOkkxxooolllllc;.                ",
        "            '::;;;;:::::clodxkkkxdolllloxO00KKKKXXXKXXXXK0kxdddddxkkkkxdoolllcccc:'                 ",
        "           .;l;'',,,;:::cclodxkkkxolc:;;;cldxkOO00OOOOkxdlllooodxxkkkkxdollcc::;;:,...              ",
        "        .';;;,.....'',;;:cloddxkkxxol:,'...'',,;;::::::;;::cllodxxxkxxdollc::;,'..',;;;,..          ",
        "     .'::;'....   ....',,;clodxxkkkxolc:;,'''''''''''',;;:cllodxxxxdddolc::;,'..   ...';:::,..      ",
        "  .';c:,.    .      .....'',:codxkOkxddollcc::;:cloollooddxxxxxxxxddolc:;,,'..        ...'coolc,.   ",
        "';cl:,..      .       .......';cldkOOxddddoddxdoxkkkkOOOOOOOOOkkxdoc;,,'''...           ..,:codxdc,.",
        "olc:'..             ..........',;:lddxddooodkkkxxxxxkkkkkkkkkkxdlc:,''......            ..,;:clddxxo",
        "cc:,..             ...............';::cccccllllllcccllolcclllcc;,'..........    .    ....,;;;clldxkO",
        ";:;,..               ...................',;;;;;;,,,,',,,,,,,','.........'....      .....';;;:clcloox",
        ":;;;,..              .'.............  ......'''..............................   .......,::;:codddoll",
        ":;;;,'....          ..''......  ...    ..........   ......... ...  .........    ......,:::::cldxxdc,",
        "c:;,'.........      .......... ..      ....    ..      ..'... ..............    .....,::ccc:codlc:cl",
        "c:;;,''.......     ........... ...     ...            ......................   ....,;;::ccclol::cllc",
        "llcc;;;''.......   ...................  ..           ..........'............    ..';;;;:ccc::::ccccl",
        "lodolcc::;''....  . .....................            .......................   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'.... .. ....... ...........     ....      .. ..................   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....     .......  ...... ...  .    ...        ...... ...''''''..  .':llc:;,'...    .';:;",
        " ..',;::;;,,'....  ......................   .   ..           ......''''''..  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''............     ... .................   .. . ....''..'''....,:c;'..       .,coooocc",
        "    .';;;;;,,,,'.....''.....      ........................... ...'''''',,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..''''...       .....................    ...'',,,'.......'..... .............',:",
        ".        ..'..',;:llc;;;,,'..           ................     ..',;,...........'',,;;............'',;",
        "...           .....',,,,,;,'..               .. ......     ..',;;'...........;c;,;,'......',',,',,;:",
        ".....             ............                           ..';;,'............,;;'......',;;;;,;:;;;;:",
        "........              ......                           ...,:;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"

    ]
    const a_i = [
        "                                        ...,;cllooddddooll:;'..                                     ",
        "                                    .';codxkkkOOkkkkkkkkkkkkxdl:,..                                 ",
        "                                ..;ldkkOOOO000OOOOOOOOOOOOOOkkkkxdl;..                              ",
        "                             ..:oxkOOOO000KKK00000000OOOOOOOOOOOOkkkdl;.                            ",
        "                           .,lxkOOOOOO000KKKKK0000000000000000OOOOOOOkkdl,.                         ",
        "                         .;lxkOOOOOOO00000KKKXXXKKKKKKKKKKKK000OOOOOOOkOkxo;.                       ",
        "                       .;oxkkkkOOOOO00KKKKKXXNNNNNNNXXXXXXKKKK00OOOkkkkkkOkko;.                     ",
        "                     .,lxkkkkkkOOO00KKXXXXXXNNNNWWWWNNNNNNXXXKK000OOkkkkkkOOkxl'                    ",
        "                   .,lxkkkkkOOOO00KKXXXXNNNWWWWWWWWWWWWWWWNNNXXKK0OOOkkkkkkkkkkd:.                  ",
        "                 .,ldkkkkkOO0000KKXXXNNNNWWWWWWWWWWWWWWWWWWWWNNXXK00OOOkkkkkkkkkxl,.                ",
        "                'cdxkkkkkOO00KKKXXXNNNWWWWWWMMMMMMMMMMMMMWWWWWWNNXKK00OOOkkkkkkkkkd:.               ",
        "              .;oxxxxxkkOO00KKKXXXNNWWWWWWMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOOkkkkkkkkxl'              ",
        "             .:dxxxxxkkOO00KKXXXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK00OOOkkkkkkkxo,.            ",
        "            .cxkxxxkkkOO00KKXXXXNNWWWWWWWMMMMMMMMMMMMMMMMMWWWWWWWWWNNXXXKK00OOkkkkkkkxo;.           ",
        "           .cxkkkkkkkOO00KKXXXNNWWWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXXKK00OOkkkkxkxo,.          ",
        "          .;dkkkkkkOOO00KKXXNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNXXKK0OOkkxxxxxl'          ",
        "          .cxkkOOOO000000KKK0000KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNNNXXK0OOkxxxxxdc.         ",
        "          .lxkOOO00KKK0kxxddolclodxO0KXNWWWWMMMMMMMMMMMMMMMMWWWWWNXXXXXXNNNNXXKK00Okxxxxdo;.        ",
        "          'okOO00KKXKOxddxxxkkxdoodxk0KXXNNWWMMMMMMMMMMMMMMWWNXK0OkddddxkO0000KKK0Okkxxddoc.        ",
        "          'okO0KKXXK0OO0KKKXXXXXKOkxddkO0KXNNWWWWWWWWWWWWWWNXK0OkxdoddxOOOOOOkkO0K0Okxddooc'        ",
        "          ,okO0KXXXXXK00KKXXXNNWWWNKOdlcldxO0KXNNWWWWWNNNXXKOkxddkO0KXNNWNNXXK0OO00Okxxdooc'        ",
        "          ,dO00KXNNNX0kOKXXK0KXNWWNNNX0xl::clxOKXNNNNNX0Oxdolodk0XNWWWWWWNNNNXXK000Okxddolc.        ",
        "          ,dO0KXXXXK0O0K00OOkO0KKKKK0OO00xl:cdOKNNWWWNKOdlcldk00KNWWWWNXKKKXXXKKK00Okxddol:.        ",
        "         .;dO0KXXXXKKK0Oxdoooc,',;cxdllx0XKxdk0XNNWWWNX0kdxO0kdodxxkO0OOOOOOO000000Okxddol:.        ",
        "        .;okO0KKXNNXXKOxo::xk:..;,,kKkolx0NX000KXNNNXXXKKKXKxlldd;.,;',odooodk000OOOkxddol,.        ",
        "        .:dOO0KKXXNNNNXXK0xdxocldddOXXKK0KXK000KXXXXXK00KXXKOO0XOc;lc':OOo;;cok0000Okxddoc'         ",
        "        .;okO00KXXNNNNNXXK0OkkOKXNNNNNNNNXK000KKXXXKKK0OO0KXXNXXXK00OxxkxddkO0KXXKK0kxddoc,.        ",
        "        ,lxkOO0KXXNNWWWWWWWWWWWWWWWWWWWNXK0000KKKKKKK00OkO0KXXNNNNWWNXKK0O0KXNNNXXK0kxddool;.       ",
        "       .cxkkO00KXXNNWWWWWWMMWWWWWWWWWNXK000000KKKKKKKK00OOOOKXXNNWWWWWWWWWWWWNNNNXK0Oxdddl,..       ",
        "       .lxkOO00KXNNNWWWWMMMWWWWWWWNNXK0000000KKXXXXXXKK00OOOO0XNNNWWWWWMMMMMWWWWNXK0Oxddo,.'.       ",
        "       'lxkkO00KXNNNWWWWWWWWWWWNNXXK00000000O00KXNNNXK000000000KXNNNWWWWWWMMWWWWNXK0Oxdddo:;.       ",
        "       .lkkkkO0KXXNNNNNNNNNNNNXKKK0kxxdddddddxkO00K0OkkkO0000OO0KKXNNNWWWWWWWWWNNXK0kxddddoc.       ",
        "       .cxxxkOO00KKKKKKKXXXXXKK000kd:;,,'...';coddddol:;:ccodddxO0KKXXNNNNWWNNNNXK0Okxddddd:.       ",
        "       .:dxxxkkkOOOOO00000KK0000OOkdl;,'',,,,'',;;::;;,'''..';:ok0000KXXXXXXXXKKK0OkxddxOko,        ",
        "       .cxxddxxxxxxxkkkkOOOOOOOkkkkxxxddddxxxxdlcllodxxdolc::codkO00000KKKK00000OOkxdddk0x:.        ",
        "       ,oxxddddooddddxxxxxkkkkxxxxxkkkkkkkOO00KKKKKKK00OOkkxxxkkkkkOOOO000OOOOkkkxddoodkxc.         ",
        "      .,llodoooooooooddddxkxxxddxxkkkkkkkkOOO00KKKKKKK0OOOkkkkkkkkkkkkkkOkkkkxxxddoolldxo,.         ",
        "       ..':oolllllloooddxxxddoodxkkkxxxxxxxkkkO00KKKK0OOkxkxkkkkkkkkkkkkkxxxxdddoolllodo:.          ",
        "          ,coollllloodddxkxddolooollc::ccclooodxxxxxxdddollodddxxxxxxkkxxxddoooolllllodo:.          ",
        "          .cooolloooddxxkkkxdoc:,',;:coodkkkOO00OkkkOOOxdoc:::cllodxdxxxxddooolllllllccc,.          ",
        "          .;lollooooodxxkkkkxdl:'.':ldkddxxkKNNNXKKXWWWXOoldo:;,,;cddxxxxxddoollllllc,...           ",
        "           ,cllllollooddxkkkkkxddoc;',:clooodxxkxddxxkkkdolol;'...;ldxxxxxddoolllllc;.              ",
        "           .:lllllllllllodxkkOkxxkkkxdxkO0000OOOkxxxxOKXXKOdc,,;:lodxkxkxxdooooolllc'.              ",
        "           .,cccccccccccloodxkOOkxxkkkkO0KKKXXNNNXXXXNNXXK00Oxxkkkkkkkkxdooooooolll;.               ",
        "            ':c:::::c:::cclodxkkkxxxxxkkOKXXXXXXXNNNNNXXXKK0kxxxkkkOkxxdooolooolllc'                ",
        "            'c:;;;;:::::::clodxkkkxdoooodk0KXXXXNNNNNNNNXKOkxdddxkkkxxdollllllcccc;.                ",
        "           .;l;,,,,;;:::::cclodxxkxdolc::codk000KKKKKK0Okdooodddxkkxxdolllllcc:::c:'..              ",
        "        .';;;,....',,;;::::cloodxxxdol:,'''',;:ccllllllc:::cloodxxxxdolllccc::;,''',;;;,..          ",
        "     .'::;'....   ..',,,;;:ccloddxxxdlc:;,'.'.........',;;:cloddxxdddolccc::;,'.. ....';:::,..      ",
        "  .';c:,.    .      ....',,;:cloddxkkdool::;;,'',,,;;;;:cloooddxddddolc:::;,'...      ...'coolc,.   ",
        "';cl:,..      .      ....'''',,;clodxkxdooolllcccoddddxxxxxxxxxxdolc;;;,,,,...          ..,:codxdc,.",
        "olc:'..              ..........',,;clodooolodkkxxxxxkkkkxxxxxddoll:,'''''.....          ..,;:clddxxo",
        "cc:,..              ...............',;;:c::cloooollooooolccllc:;;,'....''.....  .    ....,;;;clldxkO",
        ";:;,..              ....................'',;;;;;;;;;,,;;,'',,,'........'......   . .....';;;:clcloox",
        ":;;;,..               ..........  ..........''''.............................. ........,::;:codddoll",
        ":;;;,'....           ...'......  ...   ............ .............. .......''.. .......,:::::cldxxdc,",
        "c:;,'.........       .............     ..... .....   .....'... .....'..'''''.  ......,::ccc:codlc:cl",
        "c:;;,''.......       ..'...........    ....     ...   .....''........''''''..  ....,;;::ccclol::cllc",
        "llcc;;;''.......     .......... ..........           .......'...'.....'.'''..   ..';;;;:ccc::::ccccl",
        "lodolcc::;''....     .....................            .........'........'''.   ...,;::ccc::;cc;;;;:c",
        ";cllcc::::;,'...      ....... ............    .....    ................''''.   .,:lolcc:::;,...,,,,;",
        "',,;::::::;,....       .....   ...... ...   .   .....      ...... ..''''''..  .'cllc:;,'...    .';:;",
        " ..',;::;;,,'....  .. ....................      .....        .......''''''.  .;cc;,'...      ...,;;;",
        "   ..,;,,;:;,,''........................... ...........   . ......',,'''''...,:c;'..       .,coooocc",
        "    .';;;;;,,,''.....'......     ................................',,,,,,,''';:,'...       ..,;;:cldx",
        "........',,'',;:cc;'..''''...      .................'...... ....'',,,''......'..... .............',:",
        ".        ..'..',;:llc;;;,,'..          ...................  ...',;,'..........'',,;;............'',;",
        "...           .....',,,,,,,'..           ................  ..',;;,..'........;c;,;,'......',',,',,;:",
        ".....             ............                    ....    .',;;'............,;;'......',;;;;,;:;;;;:",
        "........              ......                           ...,:;'...... ....'.',....',,,,,,,;,,,;;;;;,,",
        "''.'''......                                          ...,;;'........  .........,,;;,,,,;;;;;;;;;:;,",
        ",,'..''........                                       ...,,'..................',;;;;;,,;;;;;:c:c:::;"

    ]

    return {
            blink:blink,
            silent:silent,
            smile:smile,
            ldth:l_d_th,
            mbp:m_b_p,
            wq:w_q,
            cd:c_d,
            u:u,
            ai:a_i,
            o:o,
            fv:fv,
            e:e
        }
}